### ISSUE TITLE
GET WorkerASRModelScript.js 404

### ISSUE THREAD

**Issue by yi-Xu-0100** [Haskely/WebASR#1]
控制台报错 `GET https://haskely.github.io/ASR/Model/WorkerASRModelScript.js 404`

路径应该错误了。 这个文件应该在 <https://haskely.github.io/WebASR/ASR/Model/WorkerASRModelScript.js>

**Comment by yi-Xu-0100** [comment]
https://github.com/Haskely/WebASR/blob/409202ad29a9249df2df6c9a7023f957ddc6bfff/ASR/Model/WorkerASRModel.js#L5-L13

由于入口是 main.js , 这里更改为 `const WebWorkScriptURL = './ASR/Model/WorkerASRModelScript.js'; ` 应该可以解决这个问题。

**Comment by Haskely** [comment]
匪夷所思的是，我本地测试是怎么通过的。。python的http server他给我自动修复了路径？

**Comment by Haskely** [comment]
用了个trick，兼容web worker的相对路径不一致问题已修复。https://github.com/Haskely/WebASR/commit/e667e8988f5a64b7f4c7263ffa11fbeb9177cc8b

**Comment by Haskely** [comment]
https://github.com/Haskely/WebASR/commit/e667e8988f5a64b7f4c7263ffa11fbeb9177cc8b
